name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install without hash checking
        python -m pip install --no-deps ruff black==25.1.0 isort==6.0.0
    
    - name: Lint with ruff
      run: |
        # Check for syntax errors and undefined names
        ruff check . --select=E9,F63,F7,F82 --target-version=py37
    
    - name: Check formatting with black
      run: |
        black --check --diff .
    
    - name: Check import order with isort
      run: |
        isort --check-only --profile black .